"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
import collections

def solution(s, t):
    count_dict = {}
    for ch in s:
        if ch in count_dict:
            count_dict[ch] += 1
        else:
            count_dict[ch] = 1

    for ch in t:
        if ch not in count_dict or count_dict[ch] == 0:
            return ch
        else:
            count_dict[ch] -= 1


def solution2(s, t):
    diff = collections.Counter(t) - collections.Counter(s)
    return list(diff.elements())[0]

if __name__ == '__main__':
    print solution('a', 'aa')
    print solution2('a', 'aas')

